In [44]:
import numpy as np	
# confirm alignment model
S = np.array([[1,2],
			  [2,2],
			  [3,2]])

h = np.array([[10,2],
			  [20,2],
			  [30,2],
			  [40,2],
			  [50,2],
			  [60,2]])

W = np.ones((10,3))
U = np.ones((10,6))*9

S = np.random.rand(3,2)
h = np.random.rand(6,2)
W = np.random.rand(10,3)
U = np.random.rand(10,6)

print(S.shape, h.shape, W.shape, U.shape)

(3, 2) (6, 2) (10, 3) (10, 6)


In [45]:
(W@S)+(U@h)

array([[1.87096541, 1.90609913],
       [3.10089878, 2.61209363],
       [2.0928452 , 1.48888796],
       [2.80983813, 2.3132025 ],
       [2.79189207, 2.84077633],
       [1.79792334, 2.24967817],
       [2.7736343 , 2.06791191],
       [1.82941322, 1.93916799],
       [2.40782566, 2.31579398],
       [2.58397047, 2.11645918]])

In [50]:
input = np.concat([S, h], axis=0)
weight = np.concat([W,U], axis=1)
print(weight.shape)

(10, 9)


In [47]:
weight@input

array([[1.87096541, 1.90609913],
       [3.10089878, 2.61209363],
       [2.0928452 , 1.48888796],
       [2.80983813, 2.3132025 ],
       [2.79189207, 2.84077633],
       [1.79792334, 2.24967817],
       [2.7736343 , 2.06791191],
       [1.82941322, 1.93916799],
       [2.40782566, 2.31579398],
       [2.58397047, 2.11645918]])

In [1]:
import torch
# confirm the structure of hn when bidirectional = True

model = torch.nn.RNN(input_size=3, hidden_size=10, bidirectional=True, batch_first=True)
input = torch.rand((6, 7, 3)) # batch, seq len, input size
output, hn = model(input)
# output dim = (batch, seq len, 2 * hidden_size)
# hn = (2 * num layers, batch, hidden_size)
print(output.size())
print(hn.size())

torch.Size([6, 7, 20])
torch.Size([2, 6, 10])


In [2]:
output[0, -1]

tensor([-0.2541,  0.5397,  0.3951,  0.1008,  0.2116,  0.1159,  0.0113,  0.0646,
        -0.3351, -0.1976,  0.5432, -0.2026, -0.0685,  0.4436,  0.2436, -0.2361,
        -0.0592,  0.0692,  0.0390,  0.1748], grad_fn=<SelectBackward0>)

In [3]:
output.view(6, 7, 2, 10)[0][-1] # looking at batch, seq length, direction, hidden size

tensor([[-0.2541,  0.5397,  0.3951,  0.1008,  0.2116,  0.1159,  0.0113,  0.0646,
         -0.3351, -0.1976],
        [ 0.5432, -0.2026, -0.0685,  0.4436,  0.2436, -0.2361, -0.0592,  0.0692,
          0.0390,  0.1748]], grad_fn=<SelectBackward0>)

In [4]:
hn[-2,0] # final forward

tensor([-0.2541,  0.5397,  0.3951,  0.1008,  0.2116,  0.1159,  0.0113,  0.0646,
        -0.3351, -0.1976], grad_fn=<SelectBackward0>)

In [5]:
hn[-1,0] # final backward

tensor([ 0.6079, -0.3324,  0.7227,  0.4230,  0.7632, -0.3598, -0.0692, -0.4670,
         0.5112,  0.1650], grad_fn=<SelectBackward0>)

In [7]:
output[0, 0] # initial forward, final backward

tensor([-0.1180,  0.3175, -0.0283, -0.0705, -0.1623,  0.1186, -0.0689, -0.0179,
        -0.5037,  0.0199,  0.6079, -0.3324,  0.7227,  0.4230,  0.7632, -0.3598,
        -0.0692, -0.4670,  0.5112,  0.1650], grad_fn=<SelectBackward0>)

In [8]:
output[0, -1] # final forward, initial backward

tensor([-0.2541,  0.5397,  0.3951,  0.1008,  0.2116,  0.1159,  0.0113,  0.0646,
        -0.3351, -0.1976,  0.5432, -0.2026, -0.0685,  0.4436,  0.2436, -0.2361,
        -0.0592,  0.0692,  0.0390,  0.1748], grad_fn=<SelectBackward0>)

In [6]:
torch.cat((hn[-2,0,:], hn[-1,0,:]), dim = 0)

tensor([-0.2541,  0.5397,  0.3951,  0.1008,  0.2116,  0.1159,  0.0113,  0.0646,
        -0.3351, -0.1976,  0.6079, -0.3324,  0.7227,  0.4230,  0.7632, -0.3598,
        -0.0692, -0.4670,  0.5112,  0.1650], grad_fn=<CatBackward0>)

In [49]:
import torch
import torch.nn as nn

torch.manual_seed(0)
model = nn.LSTM( input_size = 1, hidden_size = 50, num_layers  = 1 , bidirectional=True)
x = torch.rand( 50, 1, 1)
output, (hn, cn) = model(x)
# print(output[-1])
# print(hn)

In [38]:
print(output.size(), hn.size())


torch.Size([50, 1, 100]) torch.Size([2, 1, 50])
